package com.etrack;

import java.security.PublicKey;

public enum ShoppingRewards {
    TEN_DOLLAR_GIFT_CARD,
    TWENTY_DOLLAR_GIFT_CARD,
    THIRTY_DOLLAR_GIFT_CARD,
    FOURTY_DOLLAR_GIFT_CARD,
    FIFTY_DOLLAR_GIFT_CARD,
    SIXTY_DOLLAR_GIFT_CARD,
    SEVENTY_DOLLAR_GIFT_CARD,
    EIGHTY_DOLLAR_GIFT_CARD,
    NINETY_DOLLAR_GIFT_CARD,
    ONEHUNDRED_DOLLAR_GIFT_CARD;
}
